{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{ include "my-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{ include "my-app.labels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: http
{{- end }}
